### PR TITLE
Batch process selecting subgroup

### PR DESCRIPTION
**Pull request by SeanOverton**
A new batch process that lets you select a subgroup to run all the 'checked' processes on by selecting key-values in a table populated from any clinical-data-sr files in the selected directory.

### CODE REVIEW

**Review by nwilde — APPROVED** [review]
Overall really clean code, I don't know a great deal about how the batch processing works but the code looks good and is well written.

**Comment by AlexanderPadayachee** [comment]
Looks good. Docstrings are very well written. Only suggestion would be some more in line comments to describe the operation of the code.

**Review by didymo — CHANGES_REQUESTED** [review]
Where are the lines for the logging of debugging events as required by the logging policy?

**Review by didymo — CHANGES_REQUESTED** [review]
Where are the unit tests??

**Review by didymo — APPROVED** [review]

**Pull request merged**
