### PR TITLE
Remove readme installation instructions

### PR DESCRIPTION
**Pull request by Fincap**
As prompted in issue #94 , the README does not contain the most up-to-date installation instructions. Installation instructions that work for the latest OnkoDICOM version can be located in the wiki, and it is preferable to maintain the instructions in one location rather than two lest issues like this recur. I nominate that location be the GitHub wiki.

This change replaces the installation instructions provided in the README with a link to the wiki page that contains the most up-to-date instructions. It also corrects a minor spelling error in the project's description.

### CODE REVIEW

**Comment by oismaster** [comment]
I used the install instructions 2 days ago on Ubuntu and they worked
flawlessly, except that there is no mention of Plastimatch which is needed
for pyradiomics.

A

**Comment by Fincap** [comment]
Good point. Later this afternoon I will add Plastimatch installation instructions for both Windows and Ubuntu to the wiki this afternoon.

**Comment by Fincap** [comment]
Plastimatch installation instructions have been [added to the wiki](https://github.com/didymo/OnkoDICOM/wiki/Installation-Instructions#plastimatch), and a reference to these structures added to the proposed new README.

**Review by sjswerdloff — APPROVED** [review]

**Comment by sjswerdloff** [comment]
The wiki instructions for Windows has a typo (duplicate 'git clone' on the command line) 
git clone git clone https://github.com/Fincap/OnkoDICOM.git
cd OnkoDICOM

**Pull request merged**
