### PR TITLE
Add Batch Processing and Batch ISO2ROI

### PR DESCRIPTION
**Pull request by Tamookk**
This PR adds a major feature: batch processing. This allows a user to select a directory of different patients and perform one or more processes on every patient in this directory. This PR also adds the ability to batch process ISO2ROI.

Changes made:

- Addition of batch processing and batch processing GUI. This GUI has multiple tabs that allows users to select which processes to perform on a directory. Each tab has options specific to the selected batch process.
- Addition of batch ISO2ROI, including GUI which allows users to add, remove, or modify isodose levels to convert to ROIs.
- Addition of an isodose CSV specific to batch processing
- The welcome window has been changed to allow the user to choose either "Individual Patient Curation" or "Batch Processing".
- When batch processing is complete, a summary window appears that lists patient IDs, processes, if they were successful, or if they failed, why they failed. This data can be exported to a text file.
- The testing workflow has been changed to add a new folder specific for batch processing testing, so as to not interfere with other testing.

### CODE REVIEW

**Review by JThomas2020 — APPROVED** [review]
Team 19, Really Impressive! The processing was quick, everything worked as described and encountered no errors. Code is high quality. Great Job Guys!

**Comment by minhhuyxx** [comment]
@Tamookk, sorry for my delay.
- If I double click the "Individual Patient Curation" button, the program will show 2 open patient windows and then crash.
- When I used this [dataset](https://redmine.didymodesigns.com.au/attachments/732) to test this feature, I received no summary after the batch processing was completed.
- I'm not sure if this is a bug but I notice that if I run this feature several times, the summaries for previous runs are not deleted. Hence if I choose to export, all summaries will be saved to the same text file.

**Comment by Tamookk** [comment]
> If I double click the "Individual Patient Curation" button, the program will show 2 open patient windows and then crash.

I just tried myself and the program opens before I can click a second time! Do you mind testing this on the master branch? 

> When I used this dataset to test this feature, I received no summary after the batch processing was completed.

That is interesting as I just tried it myself and I got feedback for this. 

> I'm not sure if this is a bug but I notice that if I run this feature several times, the summaries for previous runs are not deleted. Hence if I choose to export, all summaries will be saved to the same text file.

This should be fixed now.

**Review by minhhuyxx — APPROVED** [review]
> Do you mind testing this on the master branch?

This problem does happen on the master branch. It's also very unlikely that someone double click on a button.

> That is interesting as I just tried it myself and I got a summary for this.

It works now. I really don't know why but it works after I read your comment. 

That's it. Great work, guys. Team 23 approved this PR.

**Pull request merged**
