### PR TITLE
 Fix error when getting sub geometry

### PR DESCRIPTION
**Pull request by celeron533**
Fixed the following error:

```
test_object = <test_model_roi.TestROI object at 0x7f09698086d0>

    def test_roi_to_geometry(test_object):
        roi_names = [roi['name']
                     for roi in test_object.
                         patient_dict_container.get("rois").values()
                     if 'ISO' not in roi['name']]
        dict_rois_contours = get_roi_contour_pixel(test_object.
                                                   patient_dict_container.
                                                   get("raw_contour"),
                                                   roi_names,
                                                   test_object.
                                                   patient_dict_container.
                                                   get("pixluts"))
        for roi_name in roi_names:
            roi_geometry = roi_to_geometry(dict_rois_contours[roi_name])
            for slice_id, geometry in roi_geometry.items():
                if geometry.geom_type == "Polygon":
                    assert len(geometry.exterior.coords) - \
                           len(dict_rois_contours[roi_name][slice_id][0]) <= 1
                else:
>                   for i in range(len(geometry)):
E                   TypeError: object of type 'MultiPolygon' has no len()

test/test_model_roi.py:206: TypeError
```

```
geometry_dict = {'1.3.12.2.1107.5.1.4.49601.30000017081104561[168](https://github.com/didymo/OnkoDICOM/actions/runs/3955459739/jobs/6773765332#step:9:169)700001084': <MULTIPOLYGON (((219 262, 221 262, 222 263, 223 264, 223 2....300000[170](https://github.com/didymo/OnkoDICOM/actions/runs/3955459739/jobs/6773765332#step:9:171)81104561168700001087': <MULTIPOLYGON (((219 247, 221 246, 223 246, 225 247, 225 247, 226 249, 227 2...>, ...}

    def geometry_to_roi(geometry_dict):
        """
        Convert the geometry object in each image slice to ROI contour data
        :param geometry_dict: A geometry dictionary
        :return: A dictionary with key-value pair {slice-uid: contour sequence}
        """
        roi_contour_sequence = {}
        for slice_id, geometry in geometry_dict.items():
            contour_sequence = []
            if geometry.geom_type == 'Polygon' and not geometry.is_empty:
                contour_data = [list(map(int, coord))
                                for coord in geometry.exterior.coords]
                contour_sequence.append(contour_data)
            elif geometry.geom_type in ['MultiPolygon', 'GeometryCollection']:
>               for sub_geometry in geometry:
E               TypeError: 'MultiPolygon' object is not iterable

src/Model/ROI.py:1240: TypeError
```

### CODE REVIEW

**Comment by celeron533** [comment]
this issue is first found in #864

**Comment by sjswerdloff** [comment]
Test is failing.
Please check to see if the test itself is broken.
Was this an API change in a version of an imported package?
If so, what was the version where it changed and let's update the version constraint for the package to x or newer.

**Comment by sjswerdloff** [comment]
> this issue is first found in #864

This project does not have an issue #864
Please clarify.  Is that a line number in a particular file?

**Comment by celeron533** [comment]
I'll check if it is caused by an unintentional package upgrade.
Close this PR for now.

**Pull request closed without merging**
