### PR TITLE
add test for dvh tab

### PR DESCRIPTION
**Pull request by tdlinh2712**
this PR adds a unit test for DVH tab in OnkoDICOM.

### CODE REVIEW

**Review by didymo — APPROVED** [review]

**Review by DuyTungHa — CHANGES_REQUESTED** [review]
The test runs forever in github pipeline. 
I think this is because the test does not account for configuration model. 
Please merge with master and make sure that all tests pass.

**Comment by sjswerdloff** [comment]
> The test runs forever in github pipeline.
> I think this is because the test does not account for configuration model.
> Please merge with master and make sure that all tests pass.

Are you asking for the author to merge master back in to their branch?
Or to merge the PR in to master?
The latter should not happen if the test is failing (including running forever) and there isn't a clear explanation why that isn't relevant.

**Comment by DuyTungHa** [comment]
@sjswerdloff I'm telling the author to pull from master and merge into their branch. This is because when I ran the test on my computer I got an error caused by a newly added feature in onkoDICOM. Probably the test hasn't accounted for this new feature.

**Comment by tdlinh2712** [comment]
> The test runs forever in github pipeline.
> I think this is because the test does not account for configuration model.
> Please merge with master and make sure that all tests pass.

I have moved the init_config fixture outside of different files so that they can be used among files, which helped avoid the configuration issue.

**Review by DuyTungHa — APPROVED** [review]

**Pull request merged**
