### PR TITLE
Bug/fix open patient window bugs

### PR DESCRIPTION
**Pull request by minhhuyxx**
This PR fixes the problems described in tickets **#1605** and **#1580** on Team 23's Redmine page.

- When a new directory is scanned, the program disables the "Confirm" button in the Open patient window.
- If more than 1 study is selected, the program will disable the "Confirm" button and display a warning message in the DICOM tree's header.

### CODE REVIEW

**Review by Tamookk — APPROVED** [review]

**Comment by sjswerdloff** [comment]
While the IHE-RO profiles state that without a scheduled study instance UID the treatment planning related objects should reuse the Study Instance UID from the CT, what recourse will the user have if the data is not contained in one study but is in fact coherent?

The organising principle should rely on the hierarchy of the objects as defined by their references.  For example, if one selects a CT, only  RTSS that reference the CT should be allowed.  Once an RTSS is selected only RT Plans that reference the RTSS should be allowed.  Alternatively, if the RT dose gets selected one could directly/automatically select the referenced plan, then automatically select the referenced RTSS and then automatically select the set of referenced image series.

**Comment by minhhuyxx** [comment]
Thanks, @sjswerdloff. The comment is very detailed and helpful. I will look into how to implement this and keep you updated.

**Comment by tdlinh2712** [comment]
> While the IHE-RO profiles state that without a scheduled study instance UID the treatment planning related objects should reuse the Study Instance UID from the CT, what recourse will the user have if the data is not contained in one study but is in fact coherent?
> 
> The organising principle should rely on the hierarchy of the objects as defined by their references. For example, if one selects a CT, only RTSS that reference the CT should be allowed. Once an RTSS is selected only RT Plans that reference the RTSS should be allowed. Alternatively, if the RT dose gets selected one could directly/automatically select the referenced plan, then automatically select the referenced RTSS and then automatically select the set of referenced image series.

Hi Stuart, I agree with you on this comment, but that sounds like an extra feature that allows users to select different types of files without being restricted within a study and it will need further research, while this PR addresses a high-priority issue reported by Dr. Miller and that he wants multiple studies selection to be disabled for now. Therefore, I suggest merging this PR to resolve the issue first, and for the feature that you suggest, we will note that for further research and implementation.

**Comment by tdlinh2712** [comment]
> > While the IHE-RO profiles state that without a scheduled study instance UID the treatment planning related objects should reuse the Study Instance UID from the CT, what recourse will the user have if the data is not contained in one study but is in fact coherent?
> > The organising principle should rely on the hierarchy of the objects as defined by their references. For example, if one selects a CT, only RTSS that reference the CT should be allowed. Once an RTSS is selected only RT Plans that reference the RTSS should be allowed. Alternatively, if the RT dose gets selected one could directly/automatically select the referenced plan, then automatically select the referenced RTSS and then automatically select the set of referenced image series.
> 
> Hi Stuart, I agree with you on this comment, but that sounds like an extra feature that allows users to select different types of files without being restricted within a study and it will need further research, while this PR addresses a high-priority issue reported by Dr. Miller and that he wants multiple studies selection to be disabled for now. Therefore, I suggest merging this PR to resolve the issue first, and for the feature that you suggest, we will note that for further research and implementation.

This suggestion has been documented in Redmine's Bug list (bug #1696).

**Pull request merged**
