### PR TITLE
GitHub CI Test Data

### PR DESCRIPTION
**Pull request by DuyTungHa**
This PR is in relation to Issue #1638 on Team23's Redmine Page. 
Now the CI process does not need the test data to be in the source code anymore. 
For local testing, you can still use the test/testdata directory. This directory is included in .gitignore file so it won't be pushed to the repository.

### CODE REVIEW

**Review by JThomas2020 — APPROVED** [review]
This requests pulls test data from the OnkoDICOM website and places it in a test folder. The other file changes fix the hardcoding path variables and changing the paths to access the files downloaded from the OnkoDIOCM website.

**Review by didymo — CHANGES_REQUESTED** [review]
Do not pull anything from the Website. The website is likely to be changed without notice.

**Comment by DuyTungHa** [comment]
> Do not pull anything from the Website. The website is likely to be changed without notice.

Do you recommend any other sources from which I can pull the test data?

**Comment by sjswerdloff** [comment]
We need a zenodo group, placement of the test data on it, and then dynamic download of it.   See PyMedPhys tests and utilities for getting test data from zenodo

**Comment by DuyTungHa** [comment]
@didymo Since you are the owner of the repository, could you go on zenodo and upload the DICOM zip files from onkoDICOM website there ? 
Here is an instruction video: https://youtu.be/S1qK_TA52e4 
Here is a sample group of testing data for PyMedPhys: https://zenodo.org/record/3870436#.YQIhYOgzaUk 
Once the test data are uploaded, I will change the github workflow to pull the test data from zenodo.

**Comment by DuyTungHa** [comment]
@didymo I have updated the pipeline to pull the test data from https://zenodo.org/record/5147737#.YQOtO44zaUk using the links that you provided in slack.

**Review by didymo — CHANGES_REQUESTED** [review]
Why is sudo being used for a user-space application?

**Comment by DuyTungHa** [comment]
@didymo The first sudo is used to install the packages required to pull the test data from zenodo. The second sudo is used to modify the permission of each file in the test data because some files are marked as read-only after unzip and the application requires both read and write access. I have removed the unnecessary sudo in unzip.

**Review by didymo — CHANGES_REQUESTED** [review]
Remove all operations requiring elevated permissions.
Meaning remove all sudo regardless of need.
Put these operations in the install wiki or another appropriate area.

**Comment by DuyTungHa** [comment]
@didymo I'm not sure but I think you may have misunderstood the process of continuous integration on GitHub. An example will illustrate this process better. 
When I push my code to GitHub, GitHub will grab my pythonapp.yml and run all the operations within that file in a GitHub CI virtual machine. If everything runs successfully, I will see the "All checks have passed" in my pull request. This is to ensure that the code has passed all the unit test cases.
The actual user will not use or run anything inside pythonapp.yml at all. The user will follow the normal installation guide on wiki to install the packages and run the application.

**Review by didymo — APPROVED** [review]

**Pull request merged**
